
services:
  elasticsearch:
    container_name: els
    image: elasticsearch:8.15.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data2:/usr/share/elasticsearch/data-node2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-20.04
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=veryStrongPass12345!
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  elasticsearch-data2:
  sqlserver-data:
